# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppLassoDense <- function(x, y, lambda, args) {
    .Call(`_hesso_rcppLassoDense`, x, y, lambda, args)
}

test_bitset <- function() {
    invisible(.Call(`_hesso_test_bitset`))
}

