# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lassoPathDense <- function(X, y, family, lambdas, lambda_type, standardize, shuffle, check_frequency, hessian_warm_starts, augment_with_gap_safe, log_hessian_update_type, path_length, maxit, tol_gap, gamma, store_dual_variables, verify_hessian, line_search, verbosity) {
    .Call(`_hesso_lassoPathDense`, X, y, family, lambdas, lambda_type, standardize, shuffle, check_frequency, hessian_warm_starts, augment_with_gap_safe, log_hessian_update_type, path_length, maxit, tol_gap, gamma, store_dual_variables, verify_hessian, line_search, verbosity)
}

lassoPathSparse <- function(X, y, family, lambdas, lambda_type, standardize, shuffle, check_frequency, hessian_warm_starts, augment_with_gap_safe, log_hessian_update_type, path_length, maxit, tol_gap, gamma, store_dual_variables, verify_hessian, line_search, verbosity) {
    .Call(`_hesso_lassoPathSparse`, X, y, family, lambdas, lambda_type, standardize, shuffle, check_frequency, hessian_warm_starts, augment_with_gap_safe, log_hessian_update_type, path_length, maxit, tol_gap, gamma, store_dual_variables, verify_hessian, line_search, verbosity)
}

